-- MySQL schema for SISTEM-PENGADUAN-PPKS
-- Jalankan dengan: mysql -u <user> -p < database/mysql/schema.sql

CREATE DATABASE IF NOT EXISTS ppks CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ppks;

CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  recording_path VARCHAR(500) NOT NULL,
  thumbnail_path VARCHAR(500) DEFAULT NULL,
  status ENUM('new','processing','completed') NOT NULL DEFAULT 'new',
  duration_seconds INT DEFAULT NULL,
  submitted_by VARCHAR(255) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  captured_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
